version: '3.8'
services:
  app:
    build:
      args:
        ARG_LINUX_LOCALE: en_US.UTF-8
        ARG_USER_UID: ${ARG_USER_UID}
        ARG_USER_GID: ${ARG_USER_GID}
        ARG_NODE_VERSION: 18.2.0
      context: .
    working_dir: /home/user/project
    extra_hosts:
      - dockerhost:host-gateway
    ports:
      - 3000:3000
    tty: true
    volumes:
      - app_local:/usr/local
      - ~/.ssh:/home/user/.ssh
      - ~/.gitconfig:/home/user/.gitconfig
      - ~/.bash_history:/home/user/.bash_history
      - .:/home/user/project
volumes:
  app_local:
