version: '3.8'
services:
  app:
    build:
      args:
        ARG_LINUX_LOCALE: en_US.UTF-8
        ARG_USER_UID: ${ARG_USER_UID}
        ARG_USER_GID: ${ARG_USER_GID}
        ARG_PYTHON_VERSION: 3.10.4
        ARG_NODE_VERSION: 18.2.0
      context: .
    working_dir: /home/user/project
    environment:
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
      FLASK_ENV: development
    extra_hosts:
      - dockerhost:host-gateway
    ports:
      - 5000:5000
    tty: true
    volumes:
      - app_local:/usr/local
      - ~/.ssh:/home/user/.ssh
      - ~/.gitconfig:/home/user/.gitconfig
      - ~/.bash_history:/home/user/.bash_history
      - .:/home/user/project
volumes:
  app_local:
